controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
import_client:
    path: /api/import_client
    controller: App\Api\Action\ImportClientAction::importCSV
    methods: [POST]